### ISSUE TITLE
Sign method undefiend 

### ISSUE THREAD

**Issue by Mihai-github** [web-token/jwt-doc#26]
Hi,
I have a problem with "The easy way". The problem is my code editor says that the sign method is undefiend and i cant figure out a method to make it work..

**Comment by Spomky** [comment]
Hi @Mihai-github,

This is because at some point the method you called return an `AbstractBuilder` due to the limitation of the `self` return statement.

You can safely assume it is a `JWSBuilder` object that provides the `sign` method.
This should be fixed with PHP8 and the [`static` return type](https://wiki.php.net/rfc/static_return_type) or the `$this` annotation
